os: linux
dist: focal
group: edge
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - aria2
      - zstd
      - xz-utils
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>/dev/null
  - docker pull fr3akyphantom/droid-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  # Download the TWRP Compressed Source Files from PhantomZone54's Release
  # > More on https://github.com/PhantomZone54/twrp_sources_norepo/releases/latest
  - TWRP_SOURCE1="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.aa" && TWRP_SOURCE2="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ab" && TWRP_SOURCE3="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ac" && TWRP_SOURCE4="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ad"
  - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE1}" 
  - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE2}" 
  - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE3}" 
  - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE4}"
  - tar --zstd -xMf MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.aa --directory $HOME/twrp/
  - tar --zstd -xMf MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ab --directory $HOME/twrp/
  - tar --zstd -xMf MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ac --directory $HOME/twrp/
  - tar --zstd -xMf MinimalOmniRecovery-twrp-9.0-norepo-20210130.tzst.ad --directory $HOME/twrp/ && rm MinimalOmniRecovery*.tzst.*
script:
  # Replace your ${_USERNAME_}, ${_REPO_SLUG_}, ${_VENDORNAME_}, ${_CODENAME_}
  - cd $HOME/twrp/
  - git clone https://github.com/jwarrior319/twrp_oneplus8t.git device/oneplus/OnePlus8T
  - rm -rf bootable/recovery && git clone https://github.com/TeamWin/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
  - ls -lAog
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/builder/twrp/:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw,z" fr3akyphantom/droid-builder:latest bash << EOF
    cd /home/builder/twrp/
    source /build/envsetup.sh
    # Choose build flavor as "eng" or "userdebug"
    BUILD_FLAVOR="eng"
    lunch omni_OnePlus8T-${BUILD_FLAVOR}
    make -j$(nproc --all) recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/OnePlus8T/recovery.img $HOME/twrp/TWRP-$version-OnePlus8T-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  # Optional: You might need to switch from https://transfer.sh to https://file.io
  # - curl -s --upload-file TWRP-$version-${_CODENAME_}-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  provider: releases
  # The secret api_key will be loaded from the environment variables
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false # Set "true" to deploy only on successful tagged commit builds
branches:
  only:
    - main # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
